# 网站标题
title: Happy Door
theme: volantis
# 网站图标，更多尺寸等图标请使用 import 方式批量导入
favicon: https://gcore.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicon.ico

language:
  - zh-CN
  - en
  - zh-TW

index_generator:
  per_page: 2   # 首页每页文章数量
  order_by: -date

import:
  head_begin:
    - <meta name="theme-color" content="#ffffff">
  head_end:
    - <meta name="hello" content="world">
  body_begin:
    - <script></script>
  body_end:
    - <script></script>
deploy:
  type: git
  repo: git@github.com:Happy-Door/InDoor.git
  branch: gh-pages

url: https://happy-door.github.io
root: /InDoor/
