debug: false
content_visibility: true
navbar:
  logo: # choose [img] or [icon + title]
    img: /InDoor/images/logo.jpg
    # icon: ~
    # title: 'Happy Door'
  menu:
    - name: 文档
      icon: fa-solid fa-book
      url: https://github.com/Happy-Door/InDoor
      target: _self

    - name: 示例
      icon: fa-solid fa-circle-play
      url: https://github.com/Happy-Door/InDoor

    - name: 帮助
      icon: fa-solid fa-circle-question
      url: https://github.com/Happy-Door/InDoor

    - name: 鸣谢
      icon: fa-solid fa-heart
      url: /README.md/

    - name: 更多
      icon: fa-solid fa-ellipsis-vertical
      rows:
        - name: 暗黑模式
          icon: fa-solid fa-moon
          toggle: darkmode
        - name: hr
        - name: 主题源码
          url: https://github.com/Happy-Door/hexo-theme-volantis
        - name: hr
        - name: 博客文章
          url: /blogs/
        - name: hr



cover:
  # height_scheme: full # full, half
  title: 'Happy Door'
  subtitle: '天下第一逍遥门'
  background: https://gcore.jsdelivr.net/gh/MHG-LAB/cron@gh-pages/bing/bing.jpg
  features:
    - name: 博客
      img: volantis-static/media/twemoji/assets/svg/1f4f0.svg
      url: /
    - name: 文档
      img: volantis-static/media/twemoji/assets/svg/1f516.svg
      url: /blogs/
      target: _self
    - name: 示例
      img: volantis-static/media/twemoji/assets/svg/1f4af.svg
      url: https://github.com/Happy-Door/InDoor
    - name: 帮助
      img: volantis-static/media/twemoji/assets/svg/1f4ac.svg
      url: https://github.com/Happy-Door/InDoor
    - name: 鸣谢
      img: volantis-static/media/twemoji/assets/svg/1f497.svg
      url: /README.md/
    - name: 归档
      img: volantis-static/media/twemoji/assets/svg/1f5c3.svg
      url: /blogs/
    - name: 源码
      img: volantis-static/media/twemoji/assets/svg/1f9ec.svg
      url: https://github.com/Happy-Door/InDoor
      target: _self

article:
  preview:
    scheme: landscape # landscape
    # pin icon for post
    pin_icon: # volantis-static/media/twemoji/assets/svg/1f4cc.svg
    # auto generate title if not exist
    auto_title: true # false, true
    # auto generate excerpt if not exist
    auto_excerpt: true # false, true
    author: true
    # show readmore button
    readmore: always # auto, always
  body:
    top_meta: [author, category, date]
    meta_library:
      author:
        avatar: volantis-static/media/org.volantis/blog/favicon/apple-touch-icon.png
        name: Happy Door
        url: https://github.com/Happy-Door/InDoor
      updated:
        title: '本页文档最后更新于：'


comments:
  service: disqus
  giscus:
    theme:
      light: "light"
      dark: "dark"
    repo: volantis-x/community
    repo-id: MDEwOlJlcG9zaXRvcnkyNDIzNjY1ODM=
    mapping: "number"
    term: "145"
    reactions-enabled: "1"
    emit-metadata: "0"
    lang: "zh-CN"
    input-position: "top"
  disqus:
    shortname: happy-door
    path: /
  valine:
    appId: FIKAgh6n0pUM08JXxhJHChVQ-MdYXbMMI
    appKey: RJGiOYFc1fBvfox4frBPpRzU
    path: /
  utterances:
    repo: volantis-x/community
    issue-number: 115
  beaudar:
    repo: volantis-x/community  
    issue-number: 115
#侧边栏
sidebar:
  for_page: [qgroup, post, category, guide]
  for_post: [toc]
  widget_library:
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-solid fa-list
        title: 本文目录
      list_number: true
      min_depth: 2
      max_depth: 5
    post:
      class: text
      display: [desktop, mobile] # [desktop, mobile]
      sticky: true
      header:
        icon: fa-solid fa-plus
        title: 社区活动
        url: /blogs/
      content:
        - '**都来听epic！**'
    # 文档导航
    guide:
      class: grid
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-solid fa-map-signs
        title: 分类导航
      fixed: true # 固定宽度
      rows:
        - name: 常见问题
          icon: fa-solid fa-question-circle
          url: /README.md/
        - name: 示例博客
          icon: fa-solid fa-play-circle
          url: /blogs/
        - name: 特别感谢
          icon: fa-solid fa-handshake
          url: /README.md/
        - name: 测试博文
          icon: fa-solid fa-file-alt
          url: /blogs/
        - name: 主题源码
          icon: fa-solid fa-file-code
          url: https://github.com/Happy-Door/hexo-theme-volantis
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: 更新日志
          icon: fa-solid fa-tags
          url: /blogs/
          rel: external nofollow noopener noreferrer
          target: _blank

    # qrcode widget
    qrcode:
      class: qrcode
      display: [desktop] # [desktop, mobile]
      header:
        icon: fa-solid fa-mobile
        title: 手机观看
      height: #64px  # Automatic height if not set
      fancybox: #true
      images:
        - volantis-static/media/org.volantis/blog/qrcode/github@volantis.png

    qgroup:
      class: text
      display: [desktop, mobile]
      header:
        icon: fa-brands fa-qq
        title: '加入 QQ 群'
      content:
        - '如果你在修炼中遇到困境，请到 [Github Issues](https://github.com/Happy-Door/InDoor/issues) 或者 [留言板](/blogs/#comments) 进行反馈'

    help:
      class: page
      display: [desktop, mobile]
      header:
        icon: fa-solid fa-headset
        title: 帮助
      pid: faq
      content: excerpt # excerpt, more, content

    news:
      class: list
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-solid fa-exclamation-triangle
        title: 近期公告
      rows:
        - name: 关于主题与文档的更新
          icon: fa-solid fa-info-circle
          url: https://github.com/volantis-x/hexo-theme-volantis/issues/215
        - name: 升级小助手
          icon: fa-solid fa-angle-double-up
          url: /blogs/#升级小助手

    docs-v2:
      class: group
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-duotone fa-list-alt
        title: 文档导航 v2

    docs-v3:
      class: group
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-duotone fa-list-alt
        title: 文档导航 v3

    docs-v4:
      class: group
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-duotone fa-list-alt
        title: 文档导航 v4

    docs-v5:
      class: group
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-duotone fa-list-alt
        title: 文档导航 v5

    docs-v6:
      class: group
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-duotone fa-list-alt
        title: 文档导航 v6

    docs-latest:
      class: group
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-duotone fa-book
        title: 文档导航 v5.0

    docs-volantis-latest:
      class: group
      display: [desktop, mobile] # [desktop, mobile]
      seo_title: Volantis
      header:
        icon: fa fa-book
        title: 文档导航 v5.0

site_footer:
  layout: [aplayer, social, source, analytics, copyright]
  copyright: '[天下第一逍遥门](hhttps://github.com/Happy-Door/InDoor/issues)'
  social:
    - img: volantis-static/media/org.volantis/icon/1322024-social-media/020-rss.svg
      url: https://github.com/Happy-Door/InDoor/issues
    - img: volantis-static/media/org.volantis/icon/1322024-social-media/029-github.svg
      url: https://github.com/Happy-Door/InDoor/issues
    - img: volantis-static/media/org.volantis/icon/1322024-social-media/010-facebook.svg
      url: https://github.com/Happy-Door/InDoor/issues
    - img: volantis-static/media/org.volantis/icon/1322024-social-media/018-twitter.svg
      url: https://github.com/Happy-Door/InDoor/issues
    - img: volantis-static/media/org.volantis/icon/1322024-social-media/045-telegram.svg
      url: https://github.com/Happy-Door/InDoor/issues
    - img: volantis-static/media/org.volantis/icon/1322024-social-media/006-youtube.svg
      url: https://github.com/Happy-Door/InDoor/issues


tag_plugins:
  # {% note text %}
  note: # style for default note:
    iconfont: 'Font Awesome 6 Pro'

plugins:
  clipboard:
    enable: true
  fontawesome: volantis-static/libs/@fortawesome/fontawesome-pro/css/all.min.css
  parallax:
    enable: true
  busuanzi:
    enable: true
  aplayer:
    enable: true
    autoplay: false
    volume: 0.4
    order: random
    # id: 4917530132 # vol red
    # id: 4917524698 # vol blue
    # id: 76244489 # vol white
    # id: 5135845906 # for Volantis 3.0
    id: 17472066121 # epic
  message:          # 音乐通知，播放、暂停、失败 时的图标
    enable: true
    icon:     # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_plugins/message.styl
      default: fa-light fa-info-circle light-blue
      quection: fa-light fa-question-circle light-blue
    copyright:  # 是否在复制时弹出版权提示
      enable: false
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'fa-brands fa-creative-commons light-blue'
    aplayer:
      enable: true
      play: fa-light fa-play light-blue
      pause: fa-light fa-pause light-blue
      error: fa-light fa-exclamation-square red
  darkmode:
    enable: true
  gitter:
    room: hexo-theme-volantis/community
  scrollreveal:
    enable: true

custom_css:
  cursor:
    enable: true
  font_smoothing: true
  
  # sidebar:
  #   effect: [shadow] # [shadow, floatable, blur]
  # body:
  #   effect: [shadow] # [shadow, floatable, blur]
  fontfamily:
    logofont:
      fontfamily: 'Dosis, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Dosis'
      url: volantis-static/media/fonts/Dosis/Dosis-Medium.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: 'Dosis, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Dosis'
      url: volantis-static/media/fonts/Dosis/Dosis-Medium.ttf
      weight: normal
      style: normal


rightmenus:
  enable: true
  order:
    - plugins.navigation  
    - hr
    - plugins.inputBox
    - plugins.seletctText
    - plugins.elementCheck
    - plugins.elementImage
    - hr
    - menus.prevNext
    - hr
    - menus.links
    - hr
    - menus.darkMode
    - hr
    - plugins.articlePage
    - hr
    - music
  options:
    iconPrefix: fa-solid
    articleShowLink: true
  plugins:
    navigation: 
      - {id: 'left', name: '转到上一页', icon: 'fa-solid fa-arrow-left PETERRIVE', event: 'history.back()', group: 'navigation'}
      - {id: 'right', name: '转到下一页', icon: 'fa-solid fa-arrow-right PETERRIVE', event: 'history.forward()', group: 'navigation'}
      - {id: 'redo', name: '刷新当前页面', icon: 'fa-solid fa-rotate-right PETERRIVE', event: 'window.location.reload()', group: 'navigation'}
      # Home 图标也替换为免费版：
      # - {id: 'home', name: '回到首页', icon: 'fa-solid fa-house PETERRIVE', link: '/', group: 'navigation'}
      - {id: 'up', name: '回到顶部', icon: 'fa-solid fa-arrow-up PETERRIVE', event: 'VolantisApp.scrolltoElement(volantis.dom.bodyAnchor)', group: 'navigation'}

    articlePage:
      - {id: 'printMode', name: '打印页面', icon: 'fa-solid fa-print TURQUOISE', event: 'printMode', group: 'articlePage'}
      - {id: 'readMode', name: '阅读模式', icon: 'fa-solid fa-book-open EMERALD', event: 'readMode', group: 'articlePage'}

    inputBox:
      - {id: 'copyPaste', name: '粘贴文本', icon: 'fa-solid fa-paste PETERRIVE', event: 'copyPaste', group: 'inputBox'}
      - {id: 'copyAll', name: '全选文本', icon: 'fa-solid fa-object-ungroup PETERRIVE', event: 'copyAll', group: 'inputBox'}
      - {id: 'copyCut', name: '剪切文本', icon: 'fa-solid fa-cut PETERRIVE', event: 'copyCut', group: 'inputBox'}

    seletctText:
      - {id: 'copyText', name: '复制文本', icon: 'fa-solid fa-copy PETERRIVE', event: 'copyText', group: 'seletctText'}
      - {id: 'searchWord', name: '站内搜索', icon: 'fa-solid fa-magnifying-glass PETERRIVE', event: 'OpenSearch(__text__)', group: 'seletctText'}
      - {id: 'bingSearch', name: '必应搜索', icon: 'fa-solid fa-magnifying-glass PETERRIVE', event: 'window.open(`https://cn.bing.com/search?q=${__text__}`)', group: 'seletctText'}

    elementCheck:
      - {id: 'openTab', name: '新标签页打开', icon: 'fa-solid fa-up-right-from-square PETERRIVE', event: 'window.open(__link__)', group: 'elementCheck'}
      - {id: 'copyLink', name: '复制链接地址', icon: 'fa-solid fa-link PETERRIVE', event: 'copyLink', group: 'elementCheck'}

    elementImage:
      - {id: 'copyImg', name: '复制图片', icon: 'fa-solid fa-image PETERRIVE', event: 'copyImg', group: 'elementImage'}
      - {id: 'googleImg', name: '谷歌识图', icon: 'fa-solid fa-images PETERRIVE', event: 'window.open(`https://www.google.com/searchbyimage?image_url=${__link__}`)', group: 'elementImage'}
    
  menus:
    links:
      - {id: 'help', name: '常见问题', icon: 'fa-solid fa-circle-question EMERALD', link: '/faqs/', group: 'link'}
      - {id: 'examples', name: '示例博客', icon: 'fa-solid fa-rss PETERRIVE', link: '/examples/', group: 'link'}
      - {id: 'contributors', name: '加入社区', icon: 'fa-solid fa-fan fa-spin AMETHYST', link: '/contributors/', group: 'link'}
      - hr
      - {id: 'source_docs', name: '本站源码', icon: 'fa-solid fa-code-branch WETASPHALT', link: 'https://github.com/Happy-Door/InDoor', group: 'link'}
      - {id: 'source_theme', name: '主题源码', icon: 'fa-solid fa-code-branch CONCRETE', link: 'https://github.com/Happy-Door/hexo-theme-volantis', group: 'link'}

    darkMode: 
      - {id: 'darkMode', name: '暗黑模式', icon: 'fa-solid fa-eclipse WISTERIA', event: 'volantis.dark.toggle()', group: 'darkMode'}

    prevNext:
      - {id: 'prev', name: '查看上一篇', icon: 'fa-solid fa-angles-left PETERRIVE', event: "volantis.rightmenu.jump('prev')", group: 'prevNext'}
      - {id: 'next', name: '查看下一篇', icon: 'fa-solid fa-angles-right PETERRIVE', event: "volantis.rightmenu.jump('next')", group: 'prevNext'}
